name: Addon
description: Add an Addon to the Marketplace
title: "[Add Addon]: "
labels: ["addon","marketplace"]
assignees:
  - mariodavid
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting an Addon to the Jmix Marketplace!
  - type: input
    id: name
    attributes:
      label: Name
      description: What is the name of the addon?
      placeholder: My new Addon
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Code
      description: What is the code of the addon?
      placeholder: my-new-addon
    validations:
      required: true